engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    channel: 'eslint-4'
    config:
      config: './.eslintrc'
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- dist/
- 'node_modules/'
- test/
