language: node_js
node_js:
- '8.11.3'
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  slack:
    secure: hA801rSo3a/ECnlViPFBqiTG1NgS1sMEExNb/MG+cTipQCAZ0Wx8baeHCC28bjv+6VZFTIrDcrIBdfPXmbgrIPm3xgmQWuhO2jLzYofPU0xol8dczlxpxBvTKwqz7oniL3nXTOfBLn5wsh0cW+lOCd+w2s5wz5hjQyGrtuOwmFo=
sudo: false
